name: CI/CD Pipeline - Testing
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' #swapped to 3.12 to work with my version
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${e0a7bf12-c188-4dc2-b497-ccc123a9dee7}
